config/routes.rb
Rails.application.routes.draw do
  
  get 'categories/index'

  get 'categories/create'

  get 'categories/destroy'

  get 'contact_us/new'

  get 'contact_us/create'

  root 'static#about'
  get '/info', to: 'static#info'
  #resources :reserve
  resources :meals
  resources :contact_us, only: [:new, :create]
  resources :reservations, only: [:new, :create]
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :meals
end

app/models/email.rb
class Email < ApplicationRecord
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :sender_email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
    validates :subject, presence: true, length: { maximum: 50 } 
    validates :content, presence: true, length: { maximum: 555 }
    
    def send_contact_us_email
        ContactUsMailer.contact_us(self).deliver_now
    end
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :category
    has_and_belongs_to_many :tags
    
    validates :name, presence: true, length: { maximum: 45 }
    validates :price, presence: true, numericality: {only_integer: true, greater_than: 0, less_than: 150}
    validates :description, length: { maximum: 100 }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :table
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { conditions: -> { 
                                  where("DATE(created_at) = ?", Date.today) } }
  validates :username, presence: true, length: { maximum: 50 } 
  validates :phone, presence: true, numericality: {only_integer: true}, length: { is: 9 }
  validates :table_id, presence: true
  validates :hour, presence: true, numericality:
                   { greater_than_or_equal_to: 6, less_than: 24}, 
                   uniqueness: { scope: :table_id, conditions: -> { 
                                 where("DATE(created_at) = ?", Date.today) } }
    
end

app/models/table.rb
class Table < ApplicationRecord
    has_many :reservation
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :meals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    def hello
        render html: "hello, world!"
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include CategoriesHelper
  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Kategoria stworzona"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "Usunięto"
    redirect_to categories_path
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def new
     @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if @email
      @email.send_contact_us_email
      flash[:info] = "E-mail został wysłany"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  private
    def email_params
      params.require(:email).permit(:sender_email, :subject, :content)
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  include MealsHelper
  
  def index
    @meals = Meal.all
    @categories = load_categories
    @categories_names = Category.all
  end

  def show
  end

  def new
    @meals = Meal.new
    @categories = load_categories

  end

  def create
    @meals = Meal.new(meal_params)
    if @meals.save
      flash.notice = "Dodano '#{@meals.name}'"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @meals = Meal.find(params[:id])
    @categories = load_categories
  end

  def update
    @meals = Meal.find(params[:id])
    @meals.update(meal_params)
    
    flash.notice = "Edytowano '#{@meals.name}'"
    
    redirect_to meals_path
  end

  def destroy
    @meals = Meal.find(params[:id])
    @meals.destroy
    
    redirect_to meals_path
  end
  
  private
    def load_categories
      Category.all
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservations = Reservation.where('hour >= ?', 1.hour.ago).
                                where("DATE(created_at) = ?", Date.today)
    @reservation = Reservation.new
  end
  
  def create
    @reservations = Reservation.where('hour >= ?', 1.hour.ago).
                                where("DATE(created_at) = ?", Date.today)
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash.notice = "Dodano rezerwację na godzinę 
                     #{@reservation.hour}:00 dla stolika nr 
                     #{@reservation.table.id}"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  private

    def reservation_params
      params.require(:reservation).permit(:username, :email, :phone, :table_id,
                                   :hour)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end

  def info
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "DONG-A"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_params
    params.require(:category).permit(:category, :name)
  end
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
  def meal_params
    params.require(:meal).permit(:name, :price, :description, :category_id)
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/categories/_category.html.haml
= category.name
%br
= link_to "delete",
          category,
          method: :delete,
          data: { confirm: "sure?" }

app/views/categories/_form.html.haml
= simple_form_for @category do |f|
  = f.input :name, placeholder: "Maksymalnie 25 znaków!"
  = f.submit "Zatwierdź"

app/views/categories/index.html.haml
=provide :title, "Kategorie"

%h1 Obecne kategorie
= render @categories
= render 'form'

app/views/contact_us/new.html.haml
= provide :title, "O Dong-A"
%h1 Napisz do nas
= form_for(@email, url: contact_us_path) do |f|
    = f.email_field :sender_email
    = f.text_field :subject
    = f.text_area :content, rows: 5
    = f.submit "Zatwierdź"

app/views/layouts/_pagemenu.html.haml
%ul
  %li
    = link_to "Strona Główna",  root_path
  %li
    = link_to "Menu",   meals_path
  %li
    = link_to "Skontaktuj się",   new_contact_u_url
  %li
    = link_to "Zarezerwuj stolik",   new_reservation_url

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "pl"}
  %head
    %meta{:charset => "utf-8"}
    %title= full_title(yield(:title))
    = stylesheet_link_tag 'application',
                          'https://fonts.googleapis.com/css?family=Jaldi|Lato',
                          media: 'all',
                          'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/pagemenu'
    = yield
    - flash.each do |message_type, message|
      = content_tag(:div, message, class: "alert alert-#{message_type}")

app/views/meals/_form.html.haml
= form_for(@meals) do |f|
  %ul
    - @meals.errors.full_messages.each do |error|
      %li= error
  = f.label :nazwa
  = f.text_field :name
  = f.label :cena
  = f.number_field :price, in: 1.0..100.0, step: 1.0
  = f.label :opis
  = f.collection_select(:category_id, Category.all, :id, :name, {prompt: "Kategoria"})
  = f.text_area :description, rows: 4
  = f.submit "Zatwierdź"

app/views/meals/_meal.html.haml
%li
  = meal.name
  = meal.price
  = meal.description
  = link_to "Usuń", meal, method: :delete, data: {confirm: "Usunąć potrawę?"}
  = link_to "Edytuj", edit_meal_path(meal)

app/views/meals/create.html.haml
%h1 Meals#create
%p Find me in app/views/meals/create.html.erb

app/views/meals/destroy.html.haml
%h1 Meals#destroy
%p Find me in app/views/meals/destroy.html.erb

app/views/meals/edit.html.haml
= provide :title, "Edytuj potrawę"
%h1 Edytuj potrawę
= render partial: 'form'

app/views/meals/index.html.haml
= provide :title, "Menu"
%h1 Karta dań
- if @meals.any?
  - @meals.group_by(&:category_id).sort.each do |value, meals|
    - @categories_names.each do |category|
      - if category.id == value
        = category.name
        = content_tag :ul do
          %ul= render meals
- else
  %p Brak dań
= link_to "Dodaj danie", new_meal_path

app/views/meals/new.html.haml
= provide :title, "Dodaj potrawę do menu"
%h1 Dodaj potrawę
= render partial: 'form'

app/views/meals/show.html.haml
%h1= @meal.name
%p= @meal.description

app/views/register/registration.html.erb
<h1>Register#registration</h1>
<p>Find me in app/views/register/registration.html.erb</p>

app/views/reservations/_form.html.haml
= form_for(@reservation) do |f|
  %ul
    - @reservation.errors.full_messages.each do |error|
      %li= error
  = f.label "Nazwisko"
  = f.text_field :username
  = f.label "Numer Telefonu"
  = f.phone_field :phone
  = f.label "Adres email"
  = f.email_field :email
  = f.collection_select(:table_id, Table.all, :id, :id, 
    {prompt: "Kategoria"})
  = f.select :hour, (9..18).to_a
  = f.submit "Rezerwuj"

app/views/reservations/new.html.haml
= provide :title, "Rezerwacja"
%h1 Zarezerwuj stolik
%p Rezerwacje możliwe są wyłącznie w dniu planowanej wizyty
- Table.all.each do |table|
  = "#{table.id} -> #{table.capacity}"
  %br
%h2 Dzisiejsze rezerwacje
- @reservations.each do |reservation|
  = reservation.table.id + reservation.date
= render partial: 'form'

app/views/reserve/_form.html.haml
= form_for(@reservation) do |f|
  %ul
    - @reservations.errors.full_messages.each do |error|
      %li= error
  = f.label "Nazwisko"
  = f.text_field :username
  = f.label "Numer Telefonu"
  = f.phone_field :phone
  = f.label "Adres email"
  = f.email_field :email
  = f.collection_select(:table_id, Table.all, :id, :name, 
    {prompt: "Kategoria"})
  = f.collection_select(:time_table_id, TimeTable.all, :id, :name, 
    {prompt: "Godzina"})
  = f.submit "Rezerwuj"